using Newtonsoft.Json; // Use Newtonsoft.Json's attribute

namespace Stocki.Infrastructure.Clients.DTOs;

public record AVStockOverviewDTO(
    [JsonProperty("Symbol")] string Symbol,
    [JsonProperty("AssetType")] string? AssetType,
    [JsonProperty("Name")] string? Name,
    [JsonProperty("Description")] string? Description,
    [JsonProperty("CIK")] string? CIK,
    [JsonProperty("Exchange")] string? Exchange,
    [JsonProperty("Currency")] string? Currency,
    [JsonProperty("Country")] string? Country,
    [JsonProperty("Sector")] string? Sector,
    [JsonProperty("Industry")] string? Industry,
    [JsonProperty("Address")] string? Address,
    [JsonProperty("OfficialSite")] string? OfficialSite,
    [JsonProperty("FiscalYearEnd")] string? FiscalYearEnd,
    [JsonProperty("LatestQuarter")] DateTime? LatestQuarter,
    [JsonProperty("MarketCapitalization")] long? MarketCapitalization,
    [JsonProperty("EBITDA")] long? EBITDA,
    [JsonProperty("PERatio")] decimal? PERatio,
    [JsonProperty("PEGRatio")] decimal? PEGRatio,
    [JsonProperty("BookValue")] decimal? BookValue,
    [JsonProperty("DividendPerShare")] decimal? DividendPerShare,
    [JsonProperty("DividendYield")] decimal? DividendYield,
    [JsonProperty("EPS")] decimal? EPS,
    [JsonProperty("RevenuePerShareTTM")] decimal? RevenuePerShareTTM,
    [JsonProperty("ProfitMargin")] decimal? ProfitMargin,
    [JsonProperty("OperatingMarginTTM")] decimal? OperatingMarginTTM,
    [JsonProperty("ReturnOnAssetsTTM")] decimal? ReturnOnAssetsTTM,
    [JsonProperty("ReturnOnEquityTTM")] decimal? ReturnOnEquityTTM,
    [JsonProperty("RevenueTTM")] long? RevenueTTM,
    [JsonProperty("GrossProfitTTM")] long? GrossProfitTTM,
    [JsonProperty("DilutedEPSTTM")] decimal? DilutedEPSTTM,
    [JsonProperty("QuarterlyEarningsGrowthYOY")] decimal? QuarterlyEarningsGrowthYOY,
    [JsonProperty("QuarterlyRevenueGrowthYOY")] decimal? QuarterlyRevenueGrowthYOY,
    [JsonProperty("AnalystTargetPrice")] decimal? AnalystTargetPrice,
    [JsonProperty("AnalystRatingStrongBuy")] int? AnalystRatingStrongBuy,
    [JsonProperty("AnalystRatingBuy")] int? AnalystRatingBuy,
    [JsonProperty("AnalystRatingHold")] int? AnalystRatingHold,
    [JsonProperty("AnalystRatingSell")] int? AnalystRatingSell,
    [JsonProperty("AnalystRatingStrongSell")] int? AnalystRatingStrongSell,
    [JsonProperty("TrailingPE")] decimal? TrailingPE,
    [JsonProperty("ForwardPE")] decimal? ForwardPE,
    [JsonProperty("PriceToSalesRatioTTM")] decimal? PriceToSalesRatioTTM,
    [JsonProperty("PriceToBookRatio")] decimal? PriceToBookRatio,
    [JsonProperty("EVToRevenue")] decimal? EVToRevenue,
    [JsonProperty("EVToEBITDA")] decimal? EVToEBITDA,
    [JsonProperty("Beta")] decimal? Beta,
    [JsonProperty("52WeekHigh")] decimal? FiftyTwoWeekHigh, // Corrected property name for C# compliance
    [JsonProperty("52WeekLow")] decimal? FiftyTwoWeekLow, // Corrected property name for C# compliance
    [JsonProperty("50DayMovingAverage")] decimal? FiftyDayMovingAverage,
    [JsonProperty("200DayMovingAverage")] decimal? TwoHundredDayMovingAverage,
    [JsonProperty("SharesOutstanding")] long? SharesOutstanding,
    [JsonProperty("DividendDate")] DateTime? DividendDate,
    [JsonProperty("ExDividendDate")] DateTime? ExDividendDate
);
