using Newtonsoft.Json;

namespace Stocki.Infrastructure.Clients.DTOs;

/// <summary>
/// The raw stock overview object which is retrieved from the api.
/// </summary>
public record AVStockOverviewDTO(
    [JsonProperty("Symbol")] string? Symbol,
    [JsonProperty("AssetType")] string? AssetType,
    [JsonProperty("Name")] string? Name,
    [JsonProperty("Description")] string? Description,
    [JsonProperty("CIK")] string? CIK,
    [JsonProperty("Exchange")] string? Exchange,
    [JsonProperty("Currency")] string? Currency,
    [JsonProperty("Country")] string? Country,
    [JsonProperty("Sector")] string? Sector,
    [JsonProperty("Industry")] string? Industry,
    [JsonProperty("Address")] string? Address,
    [JsonProperty("OfficialSite")] string? OfficialSite,
    [JsonProperty("FiscalYearEnd")] string? FiscalYearEnd,
    [JsonProperty("LatestQuarter")] string? LatestQuarter,
    [JsonProperty("MarketCapitalization")] string? MarketCapitalization,
    [JsonProperty("EBITDA")] string? EBITDA,
    [JsonProperty("PERatio")] string? PERatio,
    [JsonProperty("PEGRatio")] string? PEGRatio,
    [JsonProperty("BookValue")] string? BookValue,
    [JsonProperty("DividendPerShare")] string? DividendPerShare,
    [JsonProperty("DividendYield")] string? DividendYield,
    [JsonProperty("EPS")] string? EPS,
    [JsonProperty("RevenuePerShareTTM")] string? RevenuePerShareTTM,
    [JsonProperty("ProfitMargin")] string? ProfitMargin,
    [JsonProperty("OperatingMarginTTM")] string? OperatingMarginTTM,
    [JsonProperty("ReturnOnAssetsTTM")] string? ReturnOnAssetsTTM,
    [JsonProperty("ReturnOnEquityTTM")] string? ReturnOnEquityTTM,
    [JsonProperty("RevenueTTM")] string? RevenueTTM,
    [JsonProperty("GrossProfitTTM")] string? GrossProfitTTM,
    [JsonProperty("DilutedEPSTTM")] string? DilutedEPSTTM,
    [JsonProperty("QuarterlyEarningsGrowthYOY")] string? QuarterlyEarningsGrowthYOY,
    [JsonProperty("QuarterlyRevenueGrowthYOY")] string? QuarterlyRevenueGrowthYOY,
    [JsonProperty("AnalystTargetPrice")] string? AnalystTargetPrice,
    [JsonProperty("AnalystRatingStrongBuy")] string? AnalystRatingStrongBuy,
    [JsonProperty("AnalystRatingBuy")] string? AnalystRatingBuy,
    [JsonProperty("AnalystRatingHold")] string? AnalystRatingHold,
    [JsonProperty("AnalystRatingSell")] string? AnalystRatingSell,
    [JsonProperty("AnalystRatingStrongSell")] string? AnalystRatingStrongSell,
    [JsonProperty("TrailingPE")] string? TrailingPE,
    [JsonProperty("ForwardPE")] string? ForwardPE,
    [JsonProperty("PriceToSalesRatioTTM")] string? PriceToSalesRatioTTM,
    [JsonProperty("PriceToBookRatio")] string? PriceToBookRatio,
    [JsonProperty("EVToRevenue")] string? EVToRevenue,
    [JsonProperty("EVToEBITDA")] string? EVToEBITDA,
    [JsonProperty("Beta")] string? Beta,
    [JsonProperty("52WeekHigh")] string? FiftyTwoWeekHigh,
    [JsonProperty("52WeekLow")] string? FiftyTwoWeekLow,
    [JsonProperty("50DayMovingAverage")] string? FiftyDayMovingAverage,
    [JsonProperty("200DayMovingAverage")] string? TwoHundredDayMovingAverage,
    [JsonProperty("SharesOutstanding")] string? SharesOutstanding,
    [JsonProperty("DividendDate")] string? DividendDate,
    [JsonProperty("ExDividendDate")] string? ExDividendDate
);
